name: Lolibaba CI

on:
  push:
    branches:
      - main

jobs: 
  deploy:
    name: Deployment
    runs-on: ubuntu-latest
    steps:
      - name: Deploy on EC2
        uses: appleboy/ssh-action@v1.2.0
        with:
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          host: ${{ secrets.REMOTE_HOST }}
          username: ubuntu
          script: |
            cd /home/ubuntu/Lolibaba-bot
            ls -al
            git pull https://chymchym1905:${{ secrets.GH_PAT }}@github.com/chymchym1905/Lolibaba-bot.git main
            pip install -r -U requirements.txt
            nohup python3 main.py > output.log &
