name: Lolibaba CI

on:
  push:
    branches:
      - main

jobs: 
  deploy:
    name: Deployment
    runs-on: ubuntu-latest
    steps:
      - name: Deploy on EC2
        uses: appleboy/ssh-action@master
        with: 
          host: ${{ secrets.REMOTE_HOST }}
          username: ${{ vars.EC2USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /home/ubuntu/Lolibaba-bot
            ls -al
            git pull https://chymchym1905:${{ secrets.GH_PAT }}@github.com/chymchym1905/Lolibaba-bot.git main
            source lolibaba-venv/bin/activate
            pip install -U -r requirements.txt
            pkill python3
            nohup python3 main.py > output.log 2>&1 &
